/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rsa;

import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/**
 *
 * @author Shania
 */
public class Hal3Lain extends javax.swing.JFrame {
    JFileChooser dialog = new JFileChooser();

    /**
     * Creates new form Hal3
     */
    public Hal3Lain() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        isiData = new javax.swing.JTextField();
        ambilData = new javax.swing.JButton();
        isiSignature = new javax.swing.JTextField();
        ambilSignature = new javax.swing.JButton();
        ambilKunci = new javax.swing.JToggleButton();
        Verif = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Verify");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Sitka Display", 1, 20)); // NOI18N
        jLabel1.setText("Verification Digital Signature");

        isiData.setEditable(false);

        ambilData.setText("Load Data");
        ambilData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ambilDataActionPerformed(evt);
            }
        });

        isiSignature.setEditable(false);

        ambilSignature.setText("Load Digital Signature");
        ambilSignature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ambilSignatureActionPerformed(evt);
            }
        });

        ambilKunci.setText("Load Key");
        ambilKunci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ambilKunciActionPerformed(evt);
            }
        });

        Verif.setText("Verify");
        Verif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerifActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(isiData)
                    .addComponent(isiSignature))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ambilKunci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ambilSignature, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ambilData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel1)
                .addContainerGap(116, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Verif)
                .addGap(199, 199, 199))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isiData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ambilData))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isiSignature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ambilSignature))
                .addGap(27, 27, 27)
                .addComponent(ambilKunci)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(Verif)
                .addGap(93, 93, 93))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ambilDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ambilDataActionPerformed
        dialog.setCurrentDirectory(new File("C:\\Users\\Shania\\OneDrive\\Documents\\NetBeansProjects\\satu\\hasil\\sources"));
        int pfile = dialog.showOpenDialog(this);
        
        if(pfile == JFileChooser.APPROVE_OPTION){
        File file = dialog.getSelectedFile();
            try {
                isiData.setText("" +file);
            } catch (Exception e){
                System.out.println("Error :" +e.getMessage());
            }
        } 
    }//GEN-LAST:event_ambilDataActionPerformed

    private void ambilSignatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ambilSignatureActionPerformed
        JOptionPane.showMessageDialog(this, "Pilih file dengan format (.signature)", "Info", JOptionPane.INFORMATION_MESSAGE);
        
        dialog.setCurrentDirectory(new File("C:\\Users\\Shania\\OneDrive\\Documents\\NetBeansProjects\\satu\\hasil\\sources"));
        int pfile = dialog.showOpenDialog(this);
        
        if(pfile == JFileChooser.APPROVE_OPTION){
        File file = dialog.getSelectedFile();
            try {
                isiSignature.setText("" +file);
            } catch (Exception e){
                System.out.println("Error :" +e.getMessage());
            }
        }
    }//GEN-LAST:event_ambilSignatureActionPerformed

    private void VerifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerifActionPerformed
        if (isiData.getText().isEmpty() || isiSignature.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Pilih file terlebih dahulu.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    } else if (!ambilKunci.isSelected()) {
        JOptionPane.showMessageDialog(this, "Klik tombol Load Key terlebih dahulu.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }else{
         try {
            iniVerif.main(new String[]{});
            // JOptionPane.showMessageDialog(this, "Verifikasi selesai.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
         } catch (NoSuchAlgorithmException | IOException ex) {
            ex.printStackTrace();
            // JOptionPane.showMessageDialog(this, "Verifikasi gagal.", "Error", JOptionPane.ERROR_MESSAGE);
         }
    }
    }//GEN-LAST:event_VerifActionPerformed

    private void ambilKunciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ambilKunciActionPerformed
        if(ambilKunci.isSelected()){
            String privateKey = Halaman1.KPrivat.getText();
        } else{
            JOptionPane.showMessageDialog(this, "Tombol belum diaktifkan!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ambilKunciActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hal3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hal3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hal3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hal3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hal3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Verif;
    public static javax.swing.JButton ambilData;
    public static javax.swing.JToggleButton ambilKunci;
    public static javax.swing.JButton ambilSignature;
    public static javax.swing.JTextField isiData;
    public static javax.swing.JTextField isiSignature;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
