/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rsa;

import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/**
 *
 * @author Shania
 */
public class Hal3 extends javax.swing.JFrame {
    JFileChooser dialog = new JFileChooser();

    /**
     * Creates new form Hal3
     */
    public Hal3() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tdata = new javax.swing.JTextField();
        LData = new javax.swing.JButton();
        tsign = new javax.swing.JTextField();
        LSign = new javax.swing.JButton();
        LPub = new javax.swing.JToggleButton();
        Verif = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Verify");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Sitka Display", 1, 20)); // NOI18N
        jLabel1.setText("Verification Digital Signature");

        tdata.setEditable(false);

        LData.setText("Load Data");
        LData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LDataActionPerformed(evt);
            }
        });

        tsign.setEditable(false);

        LSign.setText("Load Digital Signature");
        LSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LSignActionPerformed(evt);
            }
        });

        LPub.setText("Load Public Key");
        LPub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LPubActionPerformed(evt);
            }
        });

        Verif.setText("Verify");
        Verif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerifActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tdata)
                    .addComponent(tsign))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LPub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LSign, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel1)
                .addContainerGap(116, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Verif)
                .addGap(199, 199, 199))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LData))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tsign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LSign))
                .addGap(27, 27, 27)
                .addComponent(LPub)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(Verif)
                .addGap(93, 93, 93))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LDataActionPerformed
        dialog.setCurrentDirectory(new File("C:\\Users\\Shania\\OneDrive\\Documents\\NetBeansProjects\\satu\\hasil\\sources"));
        int pfile = dialog.showOpenDialog(this);
        
        if(pfile == JFileChooser.APPROVE_OPTION){
        File file = dialog.getSelectedFile();
            try {
                tdata.setText("" +file);
            } catch (Exception e){
                System.out.println("Error :" +e.getMessage());
            }
        } 
    }//GEN-LAST:event_LDataActionPerformed

    private void LSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LSignActionPerformed
        JOptionPane.showMessageDialog(this, "Pilih file dengan format (.signature)", "Info", JOptionPane.INFORMATION_MESSAGE);
        
        dialog.setCurrentDirectory(new File("C:\\Users\\Shania\\OneDrive\\Documents\\NetBeansProjects\\satu\\hasil\\sources"));
        int pfile = dialog.showOpenDialog(this);
        
        if(pfile == JFileChooser.APPROVE_OPTION){
        File file = dialog.getSelectedFile();
            try {
                tsign.setText("" +file);
            } catch (Exception e){
                System.out.println("Error :" +e.getMessage());
            }
        }
    }//GEN-LAST:event_LSignActionPerformed

    private void VerifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerifActionPerformed
        if (tdata.getText().isEmpty() || tsign.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Pilih file terlebih dahulu.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }else if (!LPub.isSelected()) {
        JOptionPane.showMessageDialog(this, "Klik tombol Load Key terlebih dahulu.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }else{
       // RSAVerif.main(new String[]{});
        try {
                RSAVerification.main(new String[]{});
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(Hal3.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Hal3.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_VerifActionPerformed

    private void LPubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LPubActionPerformed
        if(LPub.isSelected()){
            String publicKey = Halaman1.KPublik.getText();
        } else{
            JOptionPane.showMessageDialog(this, "Tombol belum diaktifkan!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_LPubActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hal3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hal3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hal3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hal3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hal3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton LData;
    public static javax.swing.JToggleButton LPub;
    public static javax.swing.JButton LSign;
    private javax.swing.JButton Verif;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JTextField tdata;
    public static javax.swing.JTextField tsign;
    // End of variables declaration//GEN-END:variables
}
