package rsa;

import java.io.File;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Shania
 */
public class Halaman1 extends javax.swing.JFrame {

    /** 
     * Creates new form Halaman1
     */
    public Halaman1() {
        initComponents();
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        GetKey = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bilP = new javax.swing.JTextField();
        bilQ = new javax.swing.JTextField();
        bilE = new javax.swing.JTextField();
        SaveKey = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        KPrivat = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        KPublik = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Key");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Sitka Display", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Get Key");

        GetKey.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        GetKey.setText("Generate Key");
        GetKey.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        GetKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetKeyActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jLabel2.setText("Random Prime Numbers");

        jLabel3.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jLabel3.setText("p");

        jLabel4.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jLabel4.setText("q");

        jLabel5.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jLabel5.setText("e");

        jLabel6.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jLabel6.setText("Key");

        jLabel7.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jLabel7.setText("Public Key");

        jLabel8.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        jLabel8.setText("Privat Key");

        bilP.setEditable(false);

        bilQ.setEditable(false);

        bilE.setEditable(false);

        SaveKey.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        SaveKey.setText("Save Key");
        SaveKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveKeyActionPerformed(evt);
            }
        });

        KPrivat.setColumns(20);
        KPrivat.setLineWrap(true);
        KPrivat.setRows(5);
        jScrollPane1.setViewportView(KPrivat);

        KPublik.setColumns(20);
        KPublik.setLineWrap(true);
        KPublik.setRows(5);
        jScrollPane2.setViewportView(KPublik);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(SaveKey, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel7))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                .addComponent(jScrollPane2)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(69, 69, 69))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4))
                                    .addGap(34, 34, 34)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(bilE, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bilQ, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(34, 34, 34)
                            .addComponent(bilP, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(197, 197, 197))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(GetKey, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GetKey)
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bilP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bilQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bilE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel7)
                        .addGap(25, 25, 25))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addComponent(SaveKey)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void GetKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetKeyActionPerformed
        try {
            RSA.main(new String[]{});
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(Halaman1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Halaman1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_GetKeyActionPerformed

    private void SaveKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveKeyActionPerformed
        if(KPublik.getText().isEmpty() || KPrivat.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Klik Generate Key terlebih dahulu!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
       /* try (FileWriter writer = new FileWriter("public_key.txt")) {    
            writer.write("Public key (e,n): " + KPublik.getText());
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        try (FileWriter writer = new FileWriter("private_key.txt")) {
           writer.write("Private key (d,n): " + KPrivat.getText())  ;
        } catch (IOException ex) {
            ex.printStackTrace();
        }*/
       JFileChooser fileChooser = new JFileChooser();
       fileChooser.setDialogTitle("Simpan Kunci");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Text Files", "txt");
        fileChooser.setFileFilter(filter);
        
        JOptionPane.showMessageDialog(this, "Masukkan nama file untuk menyimpan kunci", "Info", JOptionPane.INFORMATION_MESSAGE);
        fileChooser.setCurrentDirectory(new File("C:\\Users\\Shania\\OneDrive\\Documents\\NetBeansProjects\\satu\\hasil\\key"));
        
        boolean fileSaved = false;
    while (!fileSaved) {
        int returnValue = fileChooser.showSaveDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            String publicFilePath = fileChooser.getSelectedFile().getAbsolutePath() + "_public.txt";
            String privateFilePath = fileChooser.getSelectedFile().getAbsolutePath() + "_private.txt";

            if (publicFilePath.isEmpty() || privateFilePath.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nama file tidak valid!", "Error", JOptionPane.ERROR_MESSAGE);
                continue;
            }

            File publicFile = new File(publicFilePath);
            File privateFile = new File(privateFilePath);

            if (publicFile.exists() || privateFile.exists()) {
                int overwriteOption = JOptionPane.showConfirmDialog(this, "Nama file sudah ada. Apakah Anda ingin menimpanya?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
                if (overwriteOption == JOptionPane.NO_OPTION) {
                    continue;
                }
            }

            try (FileWriter publicWriter = new FileWriter(publicFilePath)) {    
                publicWriter.write("Public key (e,n): " + KPublik.getText());
            } catch (IOException ex) {
                ex.printStackTrace();
            }

            try (FileWriter privateWriter = new FileWriter(privateFilePath)) {
                privateWriter.write("Private key (d,n): " + KPrivat.getText());
            } catch (IOException ex) {
                ex.printStackTrace();
            }
            JOptionPane.showMessageDialog(this, "Kunci telah disimpan", "Info", JOptionPane.INFORMATION_MESSAGE); 
            fileSaved = true;
            /*Halaman2 hal2 = new Halaman2();
            hal2.setVisible(true);
            this.setVisible(false);*/
            Hal2 hal2 = new Hal2();
            hal2.setVisible(true);
            this.setVisible(false);
            }else {
                    JOptionPane.showMessageDialog(this, "Simpan kunci dibatalkan", "Info", JOptionPane.INFORMATION_MESSAGE);
                    fileSaved = true;
            }  
    }
    }//GEN-LAST:event_SaveKeyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Halaman1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Halaman1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Halaman1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Halaman1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Halaman1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GetKey;
    public static javax.swing.JTextArea KPrivat;
    public static javax.swing.JTextArea KPublik;
    private javax.swing.JButton SaveKey;
    public static javax.swing.JTextField bilE;
    public static javax.swing.JTextField bilP;
    public static javax.swing.JTextField bilQ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
